version: '3'

services:
  nextdom-db:
    build:
      context: db
    image: nextdom-db
    hostname: nextdom-db
    container_name: nextdom-db
    restart: always
    ports:
    - 27017:27017
    volumes:
    - ${DATA_PATH}/data/db:/data/db
    tmpfs:
    - /nextdomstate
    environment:
    - DB_USER=${DB_USER}
    - DB_PASSWORD=${DB_PASSWORD}

  nextdom-mqtt:
    build:
      context: mqtt
    image: nextdom-mqtt
    container_name: nextdom-mqtt
    restart: always
    ports:
    - 1883:1883/tcp
    volumes:
    - ${DATA_PATH}/data/mqtt:/var/lib/mosquitto
    environment:
    - MQTT_USER=${MQTT_USER}
    - MQTT_PASSWORD=${MQTT_PASSWORD}

  nextdom-nodered:
    build:
      context: nodered
    image: nextdom-nodered
    container_name: nextdom-nodered
    restart: always
    ports:
    - 1880:1880/tcp
    depends_on:
    - nextdom-mqtt
    volumes:
    - ${DATA_PATH}/data/nodered:/root/.node-red
    environment:
    - MQTT_USER=${MQTT_USER}
    - MQTT_PASSWORD=${MQTT_PASSWORD}

  nextdom-logic:
    build:
      context: logic
    image: nextdom-logic
    container_name: nextdom-logic
    depends_on:
    - nextdom-mqtt
    - nextdom-db
    restart: always

  nextdom-api:
    build:
      context: api
    image: nextdom-api
    container_name: nextdom-api
    restart: always
    depends_on:
    - nextdom-db
    ports:
    - 3000:3000
    volumes:
    - ~/.npm:/root/.npm

networks:
  default:
    external:
      name: nextdom
